services:
  db:
    image: postgres:latest
    container_name: product_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_db
    ports:
      - 5432:5432
